export var accommodationProviders = [
    {
        user_id: 'user-accommodation-1',
        provider_id: 'provider-1',
        company_name: 'Paradise Hotels Ltd',
    },
    {
        user_id: 'user-accommodation-2',
        provider_id: 'provider-2',
        company_name: 'Beach Resorts Inc',
    },
];
export var accommodations = [
    {
        id: 'accommodation-1',
        provider_id: 'provider-1',
        name: 'Paradise Beach Hotel',
        type: ['Hotel', 'Beach Resort'],
        amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Beach Access'],
        rating: 4.7,
        account_no: 'ACC111222333',
        budget: ['Mid-range', 'Luxury'],
        location: 'Bentota',
        price_range_min: 8000.0,
        price_range_max: 25000.0,
        province: 'Southern Province',
        interests: ['Beach', 'Relaxation', 'Water Sports'],
        group_size: 4,
        num_booking_dates: 30,
        prior_bookings: 150,
    },
    {
        id: 'accommodation-2',
        provider_id: 'provider-1',
        name: 'Paradise Hill Resort',
        type: ['Resort', 'Mountain View'],
        amenities: ['Restaurant', 'WiFi', 'Hiking Trails', 'Bar'],
        rating: 4.5,
        account_no: 'ACC444555666',
        budget: ['Budget', 'Mid-range'],
        location: 'Nuwara Eliya',
        price_range_min: 5000.0,
        price_range_max: 15000.0,
        province: 'Central Province',
        interests: ['Nature', 'Hiking', 'Tea Plantations'],
        group_size: 2,
        num_booking_dates: 45,
        prior_bookings: 200,
    },
    {
        id: 'accommodation-3',
        provider_id: 'provider-2',
        name: 'Ocean Breeze Resort',
        type: ['Resort', 'Beach Front'],
        amenities: ['Pool', 'Restaurant', 'WiFi', 'Diving Center', 'Spa'],
        rating: 4.9,
        account_no: 'ACC777888999',
        budget: ['Luxury'],
        location: 'Mirissa',
        price_range_min: 15000.0,
        price_range_max: 40000.0,
        province: 'Southern Province',
        interests: ['Beach', 'Diving', 'Whale Watching'],
        group_size: 6,
        num_booking_dates: 60,
        prior_bookings: 300,
    },
];
